### ISSUE TITLE
可以分享数据集吗

### ISSUE THREAD

**Issue by Gray-gl** [yiwang454/prompt_ad_code#1]
is:issue is:open 可以分享一下AD的数据集吗？在网上找了一圈，没找到？感谢，可以有偿的，这个比赛结束了，数据集不在分享了。我肯定不会公开上传，一定保密

**Comment by yiwang454** [comment]
请联系ADReSS20 challenge组织者。我们没有分享数据集的权限。
Please contact the ADReSS20 challenge organisers for the data. We don't have any permission to share the data.
